# Generated by Django 5.0.2 on 2024-03-09 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_seasons', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INACTIVE', '휴면'), ('WAITING_DEPOSIT', '입금대기'), ('ACTIVE', '활동중'), ('SUPER', '슈퍼회원')], default='INACTIVE', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('group_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_seasons.groupseason')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '회원별 모임 시즌',
                'verbose_name_plural': '회원별 모임 시즌',
            },
        ),
    ]
