# Generated by Django 5.0.2 on 2024-03-09 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ABSENCE', '결석'), ('ATTENDANCE_NOTLATE', '출석: 지각안함'), ('ATTENDANCE_LATE', '출석: 지각'), ('PENDING', '미정')], max_length=20)),
                ('group_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_programs.groupprogram')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '회원별 모임 프로그램',
                'verbose_name_plural': '회원별 모임 프로그램',
            },
        ),
    ]
